version: "3.8"

services:
    app:
        container_name: iptc-handler
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
        ports:
            - 8088:80
