version: "3.8"

services:
    app:
        container_name: iptc-handler
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8088:80
        volumes:
            - ./:/var/www
            # - ./data:/var/www/data
